### ISSUE TITLE
Better config file

### ISSUE THREAD

**Issue by xShqdow** [SavageLabs/SavageSkyblock-OLD#19]
I would just say that the config file is not the nicest and doesn't allow a lot of features to be configurable. For example, I would suggest having missions configurable. Also having chest items in the config.

**Comment by PeachesMLG** [comment]
items in the chest is configurable through the schematic, but i intend on adding more config options

**Comment by xShqdow** [comment]
ok thx, but I'm not sure how to change the schematic. I put in my schematic in the schematic folders (inside of EpicSkyblock plugin) and deleted the starting one, but the starting one still appears. I don't think this is the right spot for this but idk
