### ISSUE TITLE
Island warps

### ISSUE THREAD

**Issue by larsvanteeffelen4** [SavageLabs/SavageSkyblock-OLD#2]
**Description of the bug**
Whenever using the warps upgrade with epicskyblock, It automaticly says maximum level reached even though i am level 0.

**To Reproduce**
1. Run command /is upgrades
2. Click Upgrade island warps

It will show maximum level reached

**Versions**
Using 1.9.3-b ES
Using 1.13.2 Spigot

**Comment by PeachesMLG** [comment]
Fixed
