### ISSUE TITLE
Plugin does not generate the island schematic

### ISSUE THREAD

**Issue by leowla** [SavageLabs/SavageSkyblock-OLD#23]
**Describe the bug**
Plugin does not create the 'island.schematic' file so when trying to create world the plugin gives an error message in chat.

**To Reproduce**
1. Issue command '/is create'
2. See error

**Expected behavior**
Create the Skyblock world

**Screenshots**
![image](https://user-images.githubusercontent.com/38830741/58770294-4eb43400-8602-11e9-9251-dcb08511e3dc.png)
[latest.log](https://github.com/ProSavage/SavageSkyblock/files/3245495/latest.log)

**Server Version (please complete the following information):**
 - Spigot Version: Paper-628 (MC 1.13.2)
 - EpicSkyblock Version: 2.0.7

**Additional context**
Problem also affects '/is home' because there is no island to teleport to.

**Comment by PeachesMLG** [comment]
fixed
