### ISSUE TITLE
World border seems to dissapear after dying

### ISSUE THREAD

**Issue by kaimokene** [SavageLabs/SavageSkyblock-OLD#4]
**Describe the bug**
The VISUAL island border seems to dissapear the non visual part is still there.

So i fell into void since i wanted to test everything and took fall damage when getting teleported back up. Then i respawned at my main world. Then went back to the island and the world border had dissapeared.

**Expected behavior**
The visual island border to not dissapear..

**Screenshots**
If really needed i can provide em but i feel like those arent needed for now. 

**Server Version (please complete the following information):**
 - Spigot Version: paper-474 1.13.2 Quite outdated i know.
 - EpicSkyblock Version 1.9.3-b

**Comment by PeachesMLG** [comment]
what happens if you do /is home, does it fix it?

**Comment by kaimokene** [comment]
Yes it did reappear when i did /is home
